import profile_photo from "./assets/profile.jpg";

export default [
  {
    id: 1,
    username: "Labeksh",
    image: profile_photo,
    skills: ["Numerology", "Tarot", "Psychic"],
    languages: ["Hindi", "English", "Spanish"],
    exp: 2,
    price: 30,
  },
  {
    id: 2,
    username: "Labeasdksh",
    image: profile_photo,
    skills: ["Numerology", "Tarot", "Psychic"],
    languages: ["Hindi", "English", "Spanish"],
    exp: 2,
    price: 40,
  },
  {
    id: 3,
    username: "Lasdabeksh",
    image: profile_photo,
    skills: ["Numerology", "Tarot", "Psychic"],
    languages: ["Hindi", "English", "Spanish"],
    exp: 5,
    price: 50,
  },
  {
    id: 4,
    username: "asLabeksh",
    image: profile_photo,
    skills: ["Numerology", "Tarot", "Psychic"],
    languages: ["Hindi", "English", "Spanish"],
    exp: 1,
    price: 20,
  },
  {
    id: 5,
    username: "fdLabeksh",
    image: profile_photo,
    skills: ["Numerology", "Tarot", "Psychic"],
    languages: ["Hindi", "English", "Spanish"],
    exp: 4,
    price: 80,
  },
  {
    id: 6,
    username: "fdLabeksh",
    image: profile_photo,
    skills: ["Numerology", "Tarot", "Psychic"],
    languages: ["Hindi", "English", "Spanish"],
    exp: 4,
    price: 80,
  },
  {
    id: 7,
    username: "fdLabeksh",
    image: profile_photo,
    skills: ["Numerology", "Tarot", "Psychic"],
    languages: ["Hindi", "English", "Spanish"],
    exp: 4,
    price: 80,
  },
];
